### ISSUE TITLE
Code can't run

### ISSUE THREAD

**Issue by shuqincao** [boreshkinai/fc-gaga#2]
" all_node_history = tf.where(all_node_history > 0, all_node_history, 0.0)" in the code

Report an error：

ValueError: Shapes must be equal rank, but are 3 and 0 for 'Select' (op: 'Select') with input shapes: [?,207,2484], [?,207,2484], [].

May I ask your tensorflow version

**Comment by boreshkinai** [comment]
I'm sorry I can't reproduce, all runs smooth on colab

**Comment by shuqincao** [comment]
Can you provide  FC_GAGA files of .py type?

**Comment by boreshkinai** [comment]
@shuqincao Hello, I have introduced run.py, which one could run as python run.py inside a docker container to reproduce the results without relying on the colab environment. Please check the updated readme, section Docker based demo. Let me know if it solves your problem. Sorry it took some time to address your concern.

**Comment by boreshkinai** [comment]
Fixed
